### ISSUE TITLE
"Weingut" auch bei Attribut wineOriginType angeben

### ISSUE THREAD

**Issue by schug96** [dh-trier/wlv#14]
Bei den Mertesdorfern Weinetiketten sind alle mit Grünhäuser beschrieben, dem Weingut. Ich kann allerdings bisher beim Attribut nur locality, also Grünhaus als Stadtteil von Mertesdorf eintragen, jedoch kein Weingut.

**Comment by christofs** [comment]
Danke für den Hinweis, jetzt sollte das möglich sein.
